---
# Training Parameters
Independent_opt: False
Target_City: 0
gpu_device: 0
learning_rate: 5e-4
learning_rate_decay: 1.2
learning_rate_decay_at_best: 60.0
learning_rate_decay_every_n_epochs: 500
epoch_num: 2000
test_every_n_epochs: 10
print_every_n_epochs: 10
BaseLineMAE: 6.5
num_nodes: 35
num_nodes2: 15
seq_len: 730
res_channel: 32
skip_channel: 16
dilated: 3
DilatedConvLayers: 4
n_hidden: 128
max_diffusion_step: 3
gconv_layers: 3
gconv_channels: 64
adj_matrix_path: ./data/adj_matrix.npy
adj_matrix_mid_scale: ./data/adj_matrix_midscale.npy
data_path: ./data/bjdata2_PM25.npy
data2_path: ./data/bj_pm25_midscale_feature.npy
input_dim_zy: 179
input_dim: 19
input_dim2: 71
ModelName: MSSTN
moving_average_factor: 0.95
InferenceLength: 24
Inference_Model: MSSTN20190802_225240

# City Information
city_number: 1
num_nodes_mid: 15
input_dim_mid: 71
adj_matrix_mid: ./data/adj/adj_matrix_mid.npy
data_path_mid: ./data/PM2.5/midscalePM2.5.npy
city_name_0: Beijing
num_nodes_0: 35
input_dim_0: 19
city_index_0: 0
adj_matrix_0: ./data/adj/adj_matrix_bj.npy
data_path_0: ./data/PM2.5/bjPM2.5.npy
city_name_1: Shijiazhuang
num_nodes_1: 7
input_dim_1: 71
city_index_1: 1
adj_matrix_1: ./data/adj/adj_matrix_sjz.npy
data_path_1: ./data/PM2.5/sjzPM2.5.npy
city_name_2: Taiyuan
num_nodes_2: 8
input_dim_2: 71
city_index_2: 8
adj_matrix_2: ./data/adj/adj_matrix_ty.npy
data_path_2: ./data/PM2.5/tyPM2.5.npy
city_name_3: Huhhot
num_nodes_3: 8
input_dim_3: 71
city_index_3: 9
adj_matrix_3: ./data/adj/adj_matrix_hhht.npy
data_path_3: ./data/PM2.5/hhhtPM2.5.npy
city_name_4: Dalian
num_nodes_4: 10
input_dim_4: 71
city_index_4: 10
adj_matrix_4: ./data/adj/adj_matrix_dl.npy
data_path_4: ./data/PM2.5/dlPM2.5.npy